crc: compile run clean

compile:
	gcc functions.c -c -o functions
	gcc driver.c functions -o driver

run:
	./driver "C:\Users\User\Documents\GitHub\CPSC-coursework\CPSC2310\Lab Work\Lab6\CPSC 2310 Fall 24.csv" output.txt

clean:
	del -f functions main