# /********************************/
#  *Samuel Pupke                  *
#  *CPSC2310 Fall 2024            *
#  *UserName: spupke              *
#  *Instructor:Dr. Yvon Feaster   *
# /********************************/


compile:
	gcc functions.c -c -o functions.o -g
	gcc driver.c -o driver functions.o -g

run:
	./driver input.txt

clean:
	del -f driver.exe functions.o
# will need to change del to rm if on linux
