cr: compile run1 run2

compile:
	g++ -std=c++17 cpsc3120homework04part01.cpp -o part01.exe -c
	g++ -std=c++17 cpsc3120homework04part02.cpp -o part02.exe -c
	g++ -std=c++17 test01.cpp -o t1main.exe part01.exe
	g++ -std=c++17 test02.cpp -o t2main.exe part02.exe

run1:
	type .\tests\part01manual.input | t1main.exe	
	type .\tests\part01test01.input | t1main.exe
	type .\tests\part01test02.input | t1main.exe
	type .\tests\part01test03.input | t1main.exe
	type .\tests\part01test04.input | t1main.exe
	type .\tests\part01test05.input | t1main.exe
	type .\tests\part01test06.input | t1main.exe
	type .\tests\part01test07.input | t1main.exe
	type .\tests\part01test08.input | t1main.exe
	type .\tests\part01test09.input | t1main.exe
	type .\tests\part01test10.input | t1main.exe
	type .\tests\part01test11.input | t1main.exe
	type .\tests\part01test12.input | t1main.exe
	type .\tests\part01test13.input | t1main.exe
	type .\tests\part01test14.input | t1main.exe
	type .\tests\part01test15.input | t1main.exe
	type .\tests\part01test16.input | t1main.exe
	type .\tests\part01test17.input | t1main.exe
	type .\tests\part01test18.input | t1main.exe
	type .\tests\part01test19.input | t1main.exe
	type .\tests\part01test20.input | t1main.exe

run2:
	type .\tests\part02test01.input | t2main.exe
	type .\tests\part02test02.input | t2main.exe
	type .\tests\part02test03.input | t2main.exe
	type .\tests\part02test04.input | t2main.exe
	type .\tests\part02test05.input | t2main.exe
	type .\tests\part02test06.input | t2main.exe
	type .\tests\part02test07.input | t2main.exe
	type .\tests\part02test08.input | t2main.exe
	type .\tests\part02test09.input | t2main.exe
	type .\tests\part02test10.input | t2main.exe
	type .\tests\part02test11.input | t2main.exe
	type .\tests\part02test12.input | t2main.exe
	type .\tests\part02test13.input | t2main.exe
	type .\tests\part02test14.input | t2main.exe
	type .\tests\part02test15.input | t2main.exe
	type .\tests\part02test16.input | t2main.exe
	type .\tests\part02test17.input | t2main.exe
	type .\tests\part02test18.input | t2main.exe
	type .\tests\part02test19.input | t2main.exe
	type .\tests\part02test20.input | t2main.exe