# Command to run the elo program using elo_testing.cpp
run:
	g++ -o elo_testing elo_testing.cpp -Wall -Werror -Wpedantic
	./elo_testing


# Command to import songs from ytmusicapi to songs.csv using importsongs.py
import:
	python importsongs.py