cr: compile run1 run2 run3


compile:
	g++ -std=c++17 OurCPSC3120Tree.cpp -c -o OurCPSC3120Tree.o
	g++ -std=c++17 test01.cpp -o t1main.exe OurCPSC3120Tree.o
	g++ -std=c++17 test02.cpp -o t2main.exe OurCPSC3120Tree.o
	g++ -std=c++17 test03.cpp -o t3main.exe OurCPSC3120Tree.o
	g++ -std=c++17 manualtest.cpp -o manual.exe OurCPSC3120Tree.o

run1:
	type .\tests\part01test01.input | t1main.exe
	type .\tests\part01test02.input | t1main.exe
	type .\tests\part01test03.input | t1main.exe
	type .\tests\part01test04.input | t1main.exe
	type .\tests\part01test05.input | t1main.exe
	type .\tests\part01test06.input | t1main.exe
	type .\tests\part01test07.input | t1main.exe
	type .\tests\part01test08.input | t1main.exe
	type .\tests\part01test09.input | t1main.exe
	type .\tests\part01test10.input | t1main.exe
	type .\tests\part01test11.input | t1main.exe
	type .\tests\part01test12.input | t1main.exe
	type .\tests\part01test13.input | t1main.exe
	type .\tests\part01test14.input | t1main.exe
	type .\tests\part01test15.input | t1main.exe

run2:
	type .\tests\part02test01.input | t2main.exe
	type .\tests\part02test02.input | t2main.exe
	type .\tests\part02test03.input | t2main.exe
	type .\tests\part02test04.input | t2main.exe
	type .\tests\part02test05.input | t2main.exe
	type .\tests\part02test06.input | t2main.exe
	type .\tests\part02test07.input | t2main.exe
	type .\tests\part02test08.input | t2main.exe
	type .\tests\part02test09.input | t2main.exe
	type .\tests\part02test10.input | t2main.exe
	type .\tests\part02test11.input | t2main.exe
	type .\tests\part02test12.input | t2main.exe
	type .\tests\part02test13.input | t2main.exe
	type .\tests\part02test14.input | t2main.exe
	type .\tests\part02test15.input | t2main.exe

run3:
	type .\tests\part03test01.input | t3main.exe
	type .\tests\part03test02.input | t3main.exe
	type .\tests\part03test03.input | t3main.exe
	type .\tests\part03test04.input | t3main.exe
	type .\tests\part03test05.input | t3main.exe
	type .\tests\part03test06.input | t3main.exe
	type .\tests\part03test07.input | t3main.exe
	type .\tests\part03test08.input | t3main.exe
	type .\tests\part03test09.input | t3main.exe
	type .\tests\part03test10.input | t3main.exe
	type .\tests\part03test11.input | t3main.exe
	type .\tests\part03test12.input | t3main.exe
	type .\tests\part03test13.input | t3main.exe
	type .\tests\part03test14.input | t3main.exe
	type .\tests\part03test15.input | t3main.exe

manual:
	type .\tests\manualtest01.input | manual.exe