cr: compile run

crc: compile run clean

compile:
	g++ alt-ghoti.cpp -o ghoti -Wall -Werror -Wpedantic

run:
	./ghoti

clean:
	del ghoti.exe

compile-old:
	g++ ghoti.cpp -o ghoti -Wall -Werror -Wpedantic
